on: [push]

jobs:
  authz0_scan:
    runs-on: ubuntu-latest
    name: Scanning
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Authz0 - Scan
        uses: hahwul/action-authz0@main
        id: authz0
        with:
          template: |
            name: sample template
            roles:
            - name: Admin1
            - name: Admin2
            - name: SuperAdmin
            - name: User
            urls:
            - url: https://www.hahwul.com
              method: GET
              contentType: ""
              body: ""
              allowRole:
              - Admin
              - Admin1
              - SuperAdmin
              - User
              denyRole: []
              alias: main
            - url: https://www.hahwul.com/about/
              method: GET
              contentType: ""
              body: ""
              allowRole:
              - Admin
              - Admin1
              - SuperAdmin
              denyRole: []
              alias: about
